title: Jhordan Figueroa Professional Site
creator: Jhordan Figueroa
email: jhordan.a.figueroa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenidos! This site contains Jhordan's projects, resume, and videos. 

# social links
twitter_username: https://twitter.com/JhordanFig
github_username:  https://github.com/JhordanFigueroa

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
